# Generated by Django 4.2.7 on 2023-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adherent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codeAdh", models.IntegerField()),
                ("nomAdh", models.CharField(max_length=30)),
                ("prenomAdh", models.CharField(max_length=30)),
                ("nbrEmpruntAdh", models.IntegerField()),
            ],
        ),
    ]
