# Generated by Django 4.2.7 on 2023-11-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MyLibraryData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateField()),
                ("date_retour_prevu", models.DateField()),
                ("date_retour_effectif", models.DateField(blank=True, null=True)),
                ("est_en_retard", models.BooleanField(default=False)),
                (
                    "adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyLibraryData.adherent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codeLivre", models.IntegerField()),
                ("titreLivre", models.CharField(max_length=30)),
                ("nbrePageLivre", models.IntegerField()),
                (
                    "adhEmprunteur",
                    models.ManyToManyField(
                        through="MyLibraryData.Emprunt", to="MyLibraryData.adherent"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emprunt",
            name="livre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MyLibraryData.livre"
            ),
        ),
    ]
