# Generated by Django 4.2.7 on 2023-11-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyLibraryData", "0004_auteur"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistiques",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalLivres", models.IntegerField()),
                ("livresEmpruntes", models.IntegerField()),
            ],
        ),
    ]
