# Generated by Django 4.2.7 on 2023-12-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MyLibraryData", "0006_livre_nbrempruntlivre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adherent",
            name="codeAdh",
        ),
        migrations.AddField(
            model_name="livre",
            name="codeAuteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MyLibraryData.auteur",
            ),
        ),
    ]
