# Generated by Django 4.2.7 on 2023-12-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyLibraryData", "0008_alter_adherent_nbrempruntadh"),
    ]

    operations = [
        migrations.AddField(
            model_name="adherent",
            name="imageSrc",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
