# Generated by Django 4.2.7 on 2023-12-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyLibraryData", "0009_adherent_imagesrc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livre",
            name="codeLivre",
        ),
        migrations.AlterField(
            model_name="adherent",
            name="nbrEmpruntAdh",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
