# Generated by Django 4.2.7 on 2023-12-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyLibraryData", "0010_remove_livre_codelivre_alter_adherent_nbrempruntadh"),
    ]

    operations = [
        migrations.AddField(
            model_name="livre",
            name="imageSrc",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
